/**
 * Maps engine effect_id / narrative SFX keys to HQ MP3 assets.
 * Samples generated by scratch/generate_sfx_hq.py (44.1 kHz, 192 kbps).
 */
export const SFX_MAP: Record<string, string> = {
  // ── Narrative / onomatopoeia ──────────────────────────────────────
  "SWOOSH!": "/audio/sfx/swoosh.mp3",
  "Screeech!": "/audio/sfx/shadow_whisper.mp3",
  "RUUUMBLE!": "/audio/sfx/stone_grind.mp3",
  "HOLY PURIFICATION": "/audio/sfx/holy_heal.mp3",
  "PALADIN CHALLENGE": "/audio/sfx/holy_heal.mp3",
  "INQUISITOR APPARITION": "/audio/sfx/shadow_whisper.mp3",
  "PORTAL GUARDIAN AWAKEN": "/audio/sfx/stone_grind.mp3",
  "Cercado!": "/audio/sfx/boss_roar.mp3",

  // ── Canonical IDs ─────────────────────────────────────────────────
  HIT_NORMAL: "/audio/sfx/hit_normal.mp3",
  HIT_CRITICAL: "/audio/sfx/hit_critical.mp3",
  LEVEL_UP: "/audio/sfx/level_up.mp3",
  CLICK: "/audio/sfx/click.mp3",
  PAGE_TURN: "/audio/sfx/page_turn.mp3",
  VICTORY: "/audio/sfx/victory_jingle.mp3",
  DEFEAT: "/audio/sfx/defeat.mp3",
  magic_cast: "/audio/sfx/magic_cast.mp3",
  arrow_release: "/audio/sfx/arrow_release.mp3",
  heal_chime: "/audio/sfx/heal_chime.mp3",
  boss_roar: "/audio/sfx/boss_roar.mp3",
  boss_phase_change: "/audio/sfx/boss_phase_change.mp3",
  party_member_down: "/audio/sfx/party_member_down.mp3",
  revive: "/audio/sfx/revive.mp3",
  holy_heal: "/audio/sfx/holy_heal.mp3",
  shadow_whisper: "/audio/sfx/shadow_whisper.mp3",
  stone_grind: "/audio/sfx/stone_grind.mp3",
  swoosh: "/audio/sfx/swoosh.mp3",
  fireball: "/audio/sfx/fireball.mp3",
  thunderstrike: "/audio/sfx/thunderstrike.mp3",
  powerful_smash: "/audio/sfx/powerful_smash.mp3",
  sneak_blade: "/audio/sfx/sneak_blade.mp3",
  venom_cut: "/audio/sfx/venom_cut.mp3",
  arcane_shield: "/audio/sfx/arcane_shield.mp3",
  fortress: "/audio/sfx/fortress.mp3",
  void_splash: "/audio/sfx/void_splash.mp3",
  grapple_pull: "/audio/sfx/grapple_pull.mp3",

  // ── Skill / companion names → dedicated samples ───────────────────
  "POWERFUL SMASH": "/audio/sfx/powerful_smash.mp3",
  "GROUND SMASH": "/audio/sfx/powerful_smash.mp3",
  "HEAVY CRASH": "/audio/sfx/powerful_smash.mp3",
  FORTRESS: "/audio/sfx/fortress.mp3",
  "FIREBALL BURN": "/audio/sfx/fireball.mp3",
  "ARCANE SHIELD": "/audio/sfx/arcane_shield.mp3",
  THUNDERSTRIKE: "/audio/sfx/thunderstrike.mp3",
  "SNEAK BLADE": "/audio/sfx/sneak_blade.mp3",
  "SHADOW WALK": "/audio/sfx/shadow_whisper.mp3",
  "VENOM CUT": "/audio/sfx/venom_cut.mp3",
  "HEAL PULSE": "/audio/sfx/heal_chime.mp3",
  "HOLY STRIKE": "/audio/sfx/holy_heal.mp3",
  "DIVINE SHIELD": "/audio/sfx/arcane_shield.mp3",
  "ARROW WHOOSH": "/audio/sfx/arrow_release.mp3",
  "GRAPPLE PULL": "/audio/sfx/grapple_pull.mp3",
  "VOID SPLASH": "/audio/sfx/void_splash.mp3",
  LIGHTNING_BOOM: "/audio/sfx/thunderstrike.mp3",
};

/** Normalize engine keys for lookup (case / punctuation tolerant). */
export function resolveSfxKey(raw: string): string | null {
  if (!raw) return null;
  if (SFX_MAP[raw]) return raw;
  const upper = raw.toUpperCase();
  if (SFX_MAP[upper]) return upper;
  const lower = raw.toLowerCase();
  if (SFX_MAP[lower]) return lower;
  const norm = raw.replace(/[^a-zA-Z0-9]/g, "").toLowerCase();
  for (const key of Object.keys(SFX_MAP)) {
    if (key.replace(/[^a-zA-Z0-9]/g, "").toLowerCase() === norm) return key;
  }
  return null;
}

/** Synth profile hints — light procedural bed under samples. */
export type SynthKind =
  | "hit"
  | "crit"
  | "magic"
  | "heal"
  | "swoosh"
  | "ui"
  | "roar"
  | "death"
  | "level"
  | "lightning"
  | "none";

export function synthKindForKey(key: string): SynthKind {
  const k = key.toLowerCase();
  if (k.includes("crit") || k.includes("smash") || k.includes("crash") || k.includes("powerful"))
    return "crit";
  if (k.includes("hit") || k.includes("blade") || k.includes("cut") || (k.includes("strike") && !k.includes("holy")))
    return "hit";
  if (k.includes("magic") || k.includes("fire") || k.includes("arcane") || k.includes("thunder"))
    return "magic";
  if (k.includes("heal") || k.includes("holy") || k.includes("divine") || k.includes("revive") || k.includes("pulse"))
    return "heal";
  if (k.includes("swoosh") || k.includes("arrow") || k.includes("walk") || k.includes("grapple"))
    return "swoosh";
  if (k.includes("click") || k.includes("page") || k.includes("ui"))
    return "ui";
  if (k.includes("roar") || k.includes("boss") || k.includes("rumble") || k.includes("phase"))
    return "roar";
  if (k.includes("defeat") || k.includes("down") || k.includes("death"))
    return "death";
  if (k.includes("level") || k.includes("victory"))
    return "level";
  if (k.includes("lightning") || k.includes("thunder"))
    return "lightning";
  return "none";
}
